// Structural/encoding proof for the TS instruction-building pipeline
// (idlCodec.ts / instructions.ts / pdas.ts): every instruction byte layout
// is checked against the real IDL generated by `anchor build` in /solana
// (discriminators, arg order, arg byte lengths) and PDA derivation is
// checked for determinism and per-seed uniqueness.
//
// This does NOT execute the compiled programs — the `litesvm` npm package
// (the JS binding for the same litesvm engine /solana's Rust tests use) only
// ships native builds for darwin/linux, not win32, so it can't load here.
// The 18 Rust litesvm tests in /solana already prove the *programs'* logic
// end-to-end; this test's job is only to prove the TS *encoding* matches
// what those programs expect byte-for-byte — same discriminators (read
// straight from the IDL, not recomputed), same field order, same widths.
import { describe, expect, it } from "vitest";
import {
  buildConfirmPickupInstruction,
  buildCreateReceiptInstruction,
  buildFundInstruction,
  buildMarkPreparingInstruction,
  buildMarkReadyInstruction,
  buildRefundInstruction,
  buildUserReleaseInstruction,
  deriveDirectoryStatePda,
  deriveEscrowConfigPda,
  deriveMerchantPda,
  deriveMerchantWalletPda,
  deriveOrderPda,
  deriveReceiptConfigPda,
  deriveReceiptPda,
  deriveVaultPda,
  encodeInstructionData,
  keccak256Utf8,
  ORDER_ESCROW_IDL,
  ORDER_ESCROW_PROGRAM_ID,
  ORDER_RECEIPT_IDL,
} from "../src/solana/index.js";
import { AccountRole } from "@solana/kit";
import { devAddress } from "../src/solanaKeys.js";

function discriminatorOf(idl: typeof ORDER_ESCROW_IDL, name: string): number[] {
  const ix = idl.instructions.find((i) => i.name === name);
  if (!ix) throw new Error(`no such instruction: ${name}`);
  return (ix as unknown as { discriminator: number[] }).discriminator;
}

// Real (dev) Ed25519 addresses, reused across unrelated "account" roles below
// purely as distinct, guaranteed-valid placeholders — this test only checks
// byte layout and account ordering, not on-chain semantics.
const buyer = devAddress(0);
const escrowConfig = devAddress(1);
const merchantWallet = devAddress(2);
const order = devAddress(3);
const usdcMint = devAddress(4);
const vault = devAddress(5);
const buyerTokenAccount = devAddress(6);

describe("order_escrow instruction encoding vs. the real IDL", () => {
  it("fund: discriminator, arg layout, and account roles/order match the IDL", () => {
    const ix = buildFundInstruction(
      { buyer, escrowConfig, merchantWallet, order, usdcMint, vault, buyerTokenAccount },
      { orderId: 1n, amount: 10_000_000n, quoteHash: new Uint8Array(32).fill(1), pickupCodeHash: new Uint8Array(32).fill(2), releaseDeadline: 123n },
    );
    expect(ix.programAddress).toBe(ORDER_ESCROW_PROGRAM_ID);
    const data = ix.data!;
    expect(Array.from(data.slice(0, 8))).toEqual(discriminatorOf(ORDER_ESCROW_IDL, "fund"));
    // discriminator(8) + order_id:u64(8) + amount:u64(8) + quote_hash:[u8;32] + pickup_code_hash:[u8;32] + release_deadline:i64(8)
    expect(data.length).toBe(8 + 8 + 8 + 32 + 32 + 8);
    // layout offsets: [disc 0..8][order_id 8..16][amount 16..24][quote_hash 24..56][pickup_code_hash 56..88][release_deadline 88..96]
    expect(Array.from(data.slice(24, 56))).toEqual(new Array(32).fill(1)); // quote_hash
    expect(Array.from(data.slice(56, 88))).toEqual(new Array(32).fill(2)); // pickup_code_hash

    const idlAccounts = ORDER_ESCROW_IDL.instructions.find((i) => i.name === "fund")!.accounts;
    expect(ix.accounts!.map((a) => a.address)).toEqual([
      buyer,
      escrowConfig,
      merchantWallet,
      order,
      usdcMint,
      vault,
      buyerTokenAccount,
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
      "11111111111111111111111111111111",
    ]);
    // buyer is writable+signer per the Rust `#[account(mut)] pub buyer: Signer<'info>`
    expect(ix.accounts![0]!.role).toBe(AccountRole.WRITABLE_SIGNER);
    expect(idlAccounts[0]!.writable).toBe(true);
    expect(idlAccounts[0]!.signer).toBe(true);
    // usdc_mint is read-only, not a signer
    expect(ix.accounts![4]!.role).toBe(AccountRole.READONLY);
  });

  it("mark_preparing / mark_ready / user_release / refund: discriminators match and args round-trip", () => {
    const merchant = devAddress(0);
    const prep = buildMarkPreparingInstruction({ merchant, merchantWallet, order }, 7n);
    expect(Array.from(prep.data!.slice(0, 8))).toEqual(discriminatorOf(ORDER_ESCROW_IDL, "mark_preparing"));
    expect(prep.data!.length).toBe(8 + 8); // discriminator + order_id:u64

    const ready = buildMarkReadyInstruction({ merchant, merchantWallet, order }, 7n);
    expect(Array.from(ready.data!.slice(0, 8))).toEqual(discriminatorOf(ORDER_ESCROW_IDL, "mark_ready"));

    const release = buildUserReleaseInstruction(
      { buyer, order, vault, merchantWallet, merchantTokenAccount: devAddress(1) },
      7n,
    );
    expect(Array.from(release.data!.slice(0, 8))).toEqual(discriminatorOf(ORDER_ESCROW_IDL, "user_release"));

    const refund = buildRefundInstruction({ caller: buyer, order, vault, buyerTokenAccount, buyer }, 7n);
    expect(Array.from(refund.data!.slice(0, 8))).toEqual(discriminatorOf(ORDER_ESCROW_IDL, "refund"));
  });

  it("confirm_pickup: encodes the pickup code as a length-prefixed UTF-8 string", () => {
    const merchant = devAddress(0);
    const code = "123456";
    const ix = buildConfirmPickupInstruction(
      { merchant, merchantWallet, order, vault, merchantTokenAccount: devAddress(1), buyer },
      7n,
      code,
    );
    const data = ix.data!;
    expect(Array.from(data.slice(0, 8))).toEqual(discriminatorOf(ORDER_ESCROW_IDL, "confirm_pickup"));
    // discriminator(8) + order_id:u64(8) + code: u32 length prefix(4) + utf8 bytes
    const lenBytes = data.slice(16, 20);
    const len = new DataView(lenBytes.buffer, lenBytes.byteOffset, 4).getUint32(0, true);
    expect(len).toBe(code.length);
    expect(new TextDecoder().decode(data.slice(20, 20 + len))).toBe(code);
  });

  it("pickup code hashing matches the on-chain keccak256 scheme (Ethereum variant, not NIST SHA3)", () => {
    // keccak256("") is a widely-published constant (e.g. Ethereum's empty
    // Merkle-Patricia-trie node hash) — an independent known-answer check
    // that this is real Keccak-256, not NIST SHA3-256 (different padding,
    // would produce a different digest for the same input).
    // The Rust program hashes pickup codes via `solana_keccak_hasher::hash`,
    // which calls the same `sol_keccak256` syscall as Ethereum's keccak256.
    expect(Buffer.from(keccak256Utf8("")).toString("hex")).toBe(
      "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
    );
    // Same function, different input -> different digest, still 32 bytes.
    const hash = keccak256Utf8("123456");
    expect(hash).toHaveLength(32);
    expect(Buffer.from(hash).toString("hex")).not.toBe("c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470");
  });
});

describe("order_receipt instruction encoding vs. the real IDL", () => {
  it("create_receipt: discriminator and two length-prefixed strings encode correctly", () => {
    const relayer = devAddress(2);
    const receiptConfig = devAddress(3);
    const receipt = devAddress(4);
    const ix = buildCreateReceiptInstruction(
      { relayer, receiptConfig, receipt },
      {
        receiptId: 1n,
        taskRef: "task-1",
        totalResearchMicroUsdc: 5_000n,
        totalMainMicroUsdc: 12_000_000n,
        completedItems: 3n,
        totalItems: 3n,
        metadataUri: "ipfs://x",
        metadataHash: new Uint8Array(32),
      },
    );
    expect(Array.from(ix.data!.slice(0, 8))).toEqual(discriminatorOf(ORDER_RECEIPT_IDL, "create_receipt"));
  });
});

describe("PDA derivation", () => {
  it("is deterministic and distinct per seed", async () => {
    const [order1] = await deriveOrderPda(1);
    const [order1Again] = await deriveOrderPda(1);
    const [order2] = await deriveOrderPda(2);
    expect(order1).toBe(order1Again);
    expect(order1).not.toBe(order2);

    const [vaultPda] = await deriveVaultPda(1);
    expect(vaultPda).not.toBe(order1); // different seed prefix -> different PDA even for the same id

    const [escrowConfigPda] = await deriveEscrowConfigPda();
    const [merchantWalletPda] = await deriveMerchantWalletPda(1);
    const [directoryStatePda] = await deriveDirectoryStatePda();
    const [merchantPda] = await deriveMerchantPda(1);
    const [receiptConfigPda] = await deriveReceiptConfigPda();
    const [receiptPda] = await deriveReceiptPda(1);
    const all = [order1, vaultPda, escrowConfigPda, merchantWalletPda, directoryStatePda, merchantPda, receiptConfigPda, receiptPda];
    expect(new Set(all).size).toBe(all.length); // all distinct
  });
});
