import { address, createKeyPairSignerFromPrivateKeyBytes, type Address, type KeyPairSigner } from "@solana/kit";

/**
 * Deterministic DEV keypair seeds (32-byte Ed25519 private key seeds) — mock/local
 * use only, generated by `scripts/precompute-dev-keys.mts`. These are NOT real
 * Solana test-validator default keys, just fixed local dev seeds so mock mode is
 * reproducible across runs. In real mode every signer key comes from env
 * (MERCHANT_<SLUG>_PRIVATE_KEY, RELAYER_PRIVATE_KEY).
 */
export const DEV_KEY_SEEDS: readonly Uint8Array[] = [
  Uint8Array.from([11, 18, 25, 32, 39, 46, 53, 60, 67, 74, 81, 88, 95, 102, 109, 116, 123, 130, 137, 144, 151, 158, 165, 172, 179, 186, 193, 200, 207, 214, 221, 228]),
  Uint8Array.from([42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 3]),
  Uint8Array.from([73, 80, 87, 94, 101, 108, 115, 122, 129, 136, 143, 150, 157, 164, 171, 178, 185, 192, 199, 206, 213, 220, 227, 234, 241, 248, 255, 6, 13, 20, 27, 34]),
  Uint8Array.from([104, 111, 118, 125, 132, 139, 146, 153, 160, 167, 174, 181, 188, 195, 202, 209, 216, 223, 230, 237, 244, 251, 2, 9, 16, 23, 30, 37, 44, 51, 58, 65]),
  Uint8Array.from([135, 142, 149, 156, 163, 170, 177, 184, 191, 198, 205, 212, 219, 226, 233, 240, 247, 254, 5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89, 96]),
  Uint8Array.from([166, 173, 180, 187, 194, 201, 208, 215, 222, 229, 236, 243, 250, 1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106, 113, 120, 127]),
  Uint8Array.from([197, 204, 211, 218, 225, 232, 239, 246, 253, 4, 11, 18, 25, 32, 39, 46, 53, 60, 67, 74, 81, 88, 95, 102, 109, 116, 123, 130, 137, 144, 151, 158]),
] as const;

/** Base58 addresses matching DEV_KEY_SEEDS, precomputed so `devAddress()` stays synchronous. */
const DEV_ADDRESSES: readonly Address[] = [
  address("FWJuUc8JMhsvinUGc5KxxZ2e9cDcobu2nePqWGQfszDc"),
  address("J2Vofii2skiNJdHC369TCnNaR92zGMnVQSfvH9YMmrJx"),
  address("ERq9141rwiq8dEefZtA8frhvnVcLfXRaQnczhtFuZtgn"),
  address("Fr9T8ebFYsZQaZLynvnpUzk8H6MkfRV4qCDG3wfkd7Pp"),
  address("CXqJco5zANz1E9Tn7zx47kuJqKbSWoFCYuewSbQ227Wm"),
  address("8EtnMrpxzqcWdUSVUWDjH2RvwAFpSyyduNTSJ2XiDHKs"),
  address("2EJA2JZqEL98u4f4JaN4FGtQPpdZ3FhJs66vJ5idzuty"),
];

export function devAddress(index: number): Address {
  const addr = DEV_ADDRESSES[index];
  if (!addr) throw new Error(`No dev key at index ${index}`);
  return addr;
}

/** Async because Ed25519 key import goes through the (Promise-based) Web Crypto API. */
export async function devKeypairSigner(index: number): Promise<KeyPairSigner> {
  const seed = DEV_KEY_SEEDS[index];
  if (!seed) throw new Error(`No dev key at index ${index}`);
  return createKeyPairSignerFromPrivateKeyBytes(seed);
}

/** Index 5 is the buyer's session wallet in mock mode; 6 is the relayer. */
export const BUYER_KEY_INDEX = 5;
export const RELAYER_KEY_INDEX = 6;
