// IDL JSON generated by `anchor build` in /solana — regenerate by copying
// from solana/idl/*.json after any program change, same pattern the old
// abis/*.ts files followed for forge build output.
import merchantDirectoryIdl from "./idl/merchant_directory.json" with { type: "json" };
import orderEscrowIdl from "./idl/order_escrow.json" with { type: "json" };
import orderReceiptIdl from "./idl/order_receipt.json" with { type: "json" };
import type { Idl } from "./idlCodec.js";

// Cast rather than rely on structural inference of the raw JSON shape —
// idlCodec.ts's `Idl` type only models the subset of the real (much larger)
// Anchor IDL schema it actually reads; treat the JSON as data, validated at
// runtime by idlCodec's lookups, same as @coral-xyz/anchor's own `Program`.
export const MERCHANT_DIRECTORY_IDL = merchantDirectoryIdl as unknown as Idl;
export const ORDER_ESCROW_IDL = orderEscrowIdl as unknown as Idl;
export const ORDER_RECEIPT_IDL = orderReceiptIdl as unknown as Idl;
