import {
  AccountRole,
  address as toAddress,
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  fetchEncodedAccount,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI16Decoder,
  getI16Encoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getI8Decoder,
  getI8Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type AccountMeta,
  type Address,
  type Decoder,
  type Encoder,
  type GetAccountInfoApi,
  type Instruction,
  type ReadonlyUint8Array,
  type Rpc,
} from "@solana/kit";

/**
 * A tiny, generic Anchor-IDL-driven instruction/account codec — the Solana
 * analog of the old viem `ORDER_ESCROW_ABI`/`readContract`/`writeContract`
 * plumbing. It reads discriminators and field layouts straight out of the
 * IDL JSON (see ./idl.ts) instead of hand-encoding borsh per instruction, so
 * it stays correct as long as the IDL (regenerated by `anchor build` in
 * /solana) matches the deployed programs.
 *
 * Deliberately untyped/dynamic (like @coral-xyz/anchor's own `Program`
 * class) — callers that want compile-time-checked call sites should wrap
 * these in typed helper functions (see solana/instructions.ts).
 */

export type IdlType =
  | "u8"
  | "u16"
  | "u32"
  | "u64"
  | "i8"
  | "i16"
  | "i32"
  | "i64"
  | "bool"
  | "string"
  | "pubkey"
  | { array: [IdlType, number] }
  | { defined: { name: string } };

interface IdlStructField {
  name: string;
  type: IdlType;
}

interface IdlTypeDef {
  name: string;
  type:
    | { kind: "struct"; fields: IdlStructField[] }
    | { kind: "enum"; variants: { name: string }[] };
}

export interface IdlInstructionAccount {
  name: string;
  writable?: boolean;
  signer?: boolean;
  address?: string;
}

interface IdlInstruction {
  name: string;
  discriminator: number[];
  accounts: IdlInstructionAccount[];
  args: IdlStructField[];
}

interface IdlAccountDef {
  name: string;
  discriminator: number[];
}

export interface Idl {
  instructions: IdlInstruction[];
  accounts?: IdlAccountDef[];
  types?: IdlTypeDef[];
}

function findType(idl: Idl, name: string): IdlTypeDef {
  const def = idl.types?.find((t) => t.name === name);
  if (!def) throw new Error(`idlCodec: unknown defined type "${name}"`);
  return def;
}

function findInstruction(idl: Idl, name: string): IdlInstruction {
  const ix = idl.instructions.find((i) => i.name === name);
  if (!ix) throw new Error(`idlCodec: unknown instruction "${name}"`);
  return ix;
}

function findAccountDef(idl: Idl, typeName: string): IdlAccountDef {
  const def = idl.accounts?.find((a) => a.name === typeName);
  if (!def) throw new Error(`idlCodec: unknown account type "${typeName}"`);
  return def;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function encoderForType(idl: Idl, type: IdlType): Encoder<any> {
  if (typeof type === "string") {
    switch (type) {
      case "u8":
        return getU8Encoder();
      case "u16":
        return getU16Encoder();
      case "u32":
        return getU32Encoder();
      case "u64":
        return getU64Encoder();
      case "i8":
        return getI8Encoder();
      case "i16":
        return getI16Encoder();
      case "i32":
        return getI32Encoder();
      case "i64":
        return getI64Encoder();
      case "bool":
        return getBooleanEncoder();
      case "string":
        return addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder());
      case "pubkey":
        return getAddressEncoder();
    }
  } else if ("array" in type) {
    const [elem, len] = type.array;
    if (elem !== "u8") throw new Error(`idlCodec: only u8 arrays are supported, got ${JSON.stringify(elem)}`);
    return fixEncoderSize(getBytesEncoder(), len);
  } else if ("defined" in type) {
    const def = findType(idl, type.defined.name);
    if (def.type.kind === "enum") {
      // Unit-variant enum -> single u8 discriminant. Callers pass the numeric variant index.
      return getU8Encoder();
    }
    if (def.type.kind === "struct") {
      return getStructEncoder(def.type.fields.map((f) => [f.name, encoderForType(idl, f.type)] as const));
    }
  }
  throw new Error(`idlCodec: unsupported type ${JSON.stringify(type)}`);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function decoderForType(idl: Idl, type: IdlType): Decoder<any> {
  if (typeof type === "string") {
    switch (type) {
      case "u8":
        return getU8Decoder();
      case "u16":
        return getU16Decoder();
      case "u32":
        return getU32Decoder();
      case "u64":
        return getU64Decoder();
      case "i8":
        return getI8Decoder();
      case "i16":
        return getI16Decoder();
      case "i32":
        return getI32Decoder();
      case "i64":
        return getI64Decoder();
      case "bool":
        return getBooleanDecoder();
      case "string":
        return addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder());
      case "pubkey":
        return getAddressDecoder();
    }
  } else if ("array" in type) {
    const [elem, len] = type.array;
    if (elem !== "u8") throw new Error(`idlCodec: only u8 arrays are supported, got ${JSON.stringify(elem)}`);
    return fixDecoderSize(getBytesDecoder(), len);
  } else if ("defined" in type) {
    const def = findType(idl, type.defined.name);
    if (def.type.kind === "enum") {
      return getU8Decoder();
    }
    if (def.type.kind === "struct") {
      return getStructDecoder(def.type.fields.map((f) => [f.name, decoderForType(idl, f.type)] as const));
    }
  }
  throw new Error(`idlCodec: unsupported type ${JSON.stringify(type)}`);
}

/** 8-byte Anchor discriminator + borsh-encoded args, in IDL declaration order. */
export function encodeInstructionData(idl: Idl, instructionName: string, args: Record<string, unknown>): Uint8Array {
  const ix = findInstruction(idl, instructionName);
  const discriminator = Uint8Array.from(ix.discriminator);
  if (ix.args.length === 0) return discriminator;
  const fields = ix.args.map((a) => [a.name, encoderForType(idl, a.type)] as const);
  const argBytes = getStructEncoder(fields).encode(args);
  const out = new Uint8Array(discriminator.length + argBytes.length);
  out.set(discriminator, 0);
  out.set(argBytes, discriminator.length);
  return out;
}

/** Checks the 8-byte account discriminator and borsh-decodes the remaining fields per the IDL's matching `types` entry. */
export function decodeAccountData<T = Record<string, unknown>>(
  idl: Idl,
  typeName: string,
  data: Uint8Array | ReadonlyUint8Array,
): T {
  const accountDef = findAccountDef(idl, typeName);
  const discriminator = accountDef.discriminator;
  for (let i = 0; i < discriminator.length; i++) {
    if (data[i] !== discriminator[i]) {
      throw new Error(`idlCodec: account discriminator mismatch decoding "${typeName}"`);
    }
  }
  const def = findType(idl, typeName);
  if (def.type.kind !== "struct") throw new Error(`idlCodec: account type "${typeName}" is not a struct`);
  const fields = def.type.fields.map((f) => [f.name, decoderForType(idl, f.type)] as const);
  return getStructDecoder(fields).decode(data.slice(discriminator.length)) as T;
}

/**
 * Fetches an account over RPC and decodes it in one call. Returns `undefined`
 * if the account doesn't exist (mirrors the old `getOrder().orderId === 0n`
 * "not found" check from the EVM version's `readContract`).
 */
export async function fetchAndDecodeAccount<T = Record<string, unknown>>(
  rpc: Rpc<GetAccountInfoApi>,
  idl: Idl,
  typeName: string,
  address: Address,
): Promise<T | undefined> {
  const account = await fetchEncodedAccount(rpc, address);
  if (!account.exists) return undefined;
  return decodeAccountData<T>(idl, typeName, account.data);
}

/**
 * Builds a full transaction {@link Instruction}. Accounts fixed in the IDL
 * (e.g. `token_program`, `system_program`) are filled in automatically;
 * `accounts` only needs to supply the ones that vary per call (matched by
 * IDL account name).
 */
export function buildInstruction(
  idl: Idl,
  programAddress: Address,
  instructionName: string,
  accounts: Record<string, Address>,
  args: Record<string, unknown> = {},
): Instruction {
  const ix = findInstruction(idl, instructionName);
  const accountMetas: AccountMeta[] = ix.accounts.map((a) => {
    const resolvedAddress = a.address ? toAddress(a.address) : accounts[a.name];
    if (!resolvedAddress) {
      throw new Error(`idlCodec: missing account "${a.name}" for instruction "${instructionName}"`);
    }
    const role = a.writable
      ? a.signer
        ? AccountRole.WRITABLE_SIGNER
        : AccountRole.WRITABLE
      : a.signer
        ? AccountRole.READONLY_SIGNER
        : AccountRole.READONLY;
    return { address: resolvedAddress, role };
  });
  return {
    programAddress,
    accounts: accountMetas,
    data: encodeInstructionData(idl, instructionName, args),
  };
}
